name: Docs

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    docs:
        name: Publish docs / OS ${{ matrix.os }} / Node ${{ matrix.node }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [20.x]

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}

            - run: |
                  npm install
                  npm run docs

            - name: Publish
              uses: peaceiris/actions-gh-pages@v4
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: docs
                  force_orphan: true
                  commit_message: 'docs: update'
