name: Release

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    release:
        name: Release / Node ${{ matrix.node }}
        strategy:
            matrix:
                node: [20.x]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}

            - run: |
                  npm i
                  npm run build

            - name: Create a release
              run: npx semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
